linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 10
    max-complexity: 12
  maligned:
    suggest-new: true
  dupl:
    threshold: 500
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/maximilian.mueller-67/service-index
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting
      - yodaStyleExpr
      - unnamedResult
      - commentedOutCode
      - assignOp
      - docStub

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - gocyclo
    - gocritic
    - interfacer
    - wsl
    - funlen
    - unused
    - gomnd
    - godot
    - exhaustivestruct
    - exhaustruct
    - varnamelen
    - gci
run:
  # default concurrency is a available CPU number
  concurrency: 1
#  skip-dirs:
#    - test/testdata_etc

issues:
  #  exclude-use-default: false
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
